name: Build and Push Image

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags:
            ${{ secrets.DOCKERHUB_USERNAME }}/filebrowser:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/filebrowser:latest

          build-args: |
            USER_ID='php'
            GROUP_ID='php'

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script:
            docker system prune -f &&
            cd /var/www/xdsoft &&
            docker-compose pull connector &&
            docker-compose restart connector &&
            docker-compose up -d
